Created PhysicsManager class. Refactored MathHelper and started working on a PhysicsHelper file. Still confused on why its not working, will check back with sir to see what i am missing. File Error C1033